#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const currentDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(currentDir, '..');

// Read the built HTML
const htmlPath = join(projectRoot, 'dist/src/ui/mcp-app.html');
const htmlContent = readFileSync(htmlPath, 'utf-8');

// Escape for TypeScript template literal
// We need to escape: backticks (`), backslashes (\), and ${
const escapedHtml = htmlContent
  .replace(/\\/g, '\\\\')  // Escape backslashes first
  .replace(/`/g, '\\`')     // Escape backticks
  .replace(/\$/g, '\\$');   // Escape dollar signs

// Create the cloudflare-worker.ts content
const workerContent = `import { createMcpHandler } from 'agents/mcp';
import { createServer } from '../core/create-server.js';

// Full embedded HTML bundle (generated from dist/src/ui/mcp-app.html)
// This file is auto-generated by scripts/embed-html.js during build
const EMBEDDED_HTML = \`${escapedHtml}\`;

const mcpServer = createServer({
  htmlLoader: () => EMBEDDED_HTML,
});

export default {
  fetch: createMcpHandler(mcpServer),
};
`;

// Write the updated cloudflare-worker.ts
const workerPath = join(projectRoot, 'src/entry/cloudflare-worker.ts');
writeFileSync(workerPath, workerContent, 'utf-8');

console.log('✅ Embedded HTML into cloudflare-worker.ts');
console.log(`   HTML size: ${htmlContent.length.toLocaleString()} bytes`);
console.log(`   Worker size: ${workerContent.length.toLocaleString()} bytes`);
